network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: true
      optional: true
  wifis:
    wlan0:
      dhcp4: true
      dhcp6: true
      optional: true
      access-points:
        # Uncomment and configure your WiFi network
        # "YourWiFiNetwork":
        #   password: "YourWiFiPassword"
        #   mode: infrastructure
